#include <iostream>
using namespace std;
main(){
int num1,num2,num3,num4,num5,num6,num7,num8,num9,num10,num11,num12,num13,num14,num15,first5,mid5,last5,add,subtract;
cout <<"Enter Number1:  ";
cin >>num1;
cout <<"Enter Number2:  ";
cin >>num2;
cout <<"Enter Number3:  ";
cin >>num3;
cout <<"Enter Number4:  ";
cin >>num4;
cout <<"Enter Number5:  ";
cin >>num5;
cout <<"Enter Number6:  ";
cin >>num6;
cout <<"Enter Number7:  ";
cin >>num7;
cout <<"Enter Number8:  ";
cin >>num8;
cout <<"Enter Number9:  ";
cin >>num9;
cout <<"Enter Number10: ";
cin >>num10;
cout <<"Enter Number11: ";
cin >>num11;
cout <<"Enter Number12: ";
cin >>num12;
cout <<"Enter Number13: ";
cin >>num13;
cout <<"Enter Number14: ";
cin >>num14;
cout <<"Enter Number15: ";
cin >>num15;
first5=num1+num2+num3+num4+num5;
cout <<first5<<endl;
mid5=num6*num7*num8*num9*num10;
cout <<mid5<<endl;
last5=num15-num14-num13-num12-num11;
cout <<last5<<endl;
add=first5+mid5;
subtract=add-last5;
cout <<"Output is: "<<subtract;
}                                                                                       